project:
  type: book

book:
  title: "The Title of the Thesis"
  author: "Jane Doe"
  date: "30/10/2023"
  chapters:
    - index.qmd
    - declaration.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  output-file: "JaneDoe_thesis"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    template-partials: 
      - partials/before-body.tex
      - partials/toc.tex
    toc: true
    toc-title: "This might be the title of the TOC"
